" Joshua Zepf

set nocompatible              " be iMproved, required
filetype off                  " required

" Colors
set t_Co=256
colorscheme molokai
syntax enable " Enable syntax processing
let g:airline_theme='simple'

" Spacing and Tabs
set tabstop=4 " Number of spaces per tab
set softtabstop=4 " Number of spaces per tab while editing
set shiftwidth=4
set expandtab " Makes tabs into 4 spaces
set autoindent
set smartindent
set cindent


" UI Config
set number " Shows line numbers
set relativenumber " Shows line numbers relative to the visual line
set showcmd " Shows command in bottom bar
set cursorline " Highlight current line
filetype indent on " Load filetype-specific indent files
set wildmenu " Visual autocomplete for command menu
set lazyredraw " Redraw only when we need to
set showmatch " Shows matching {,[,(


" Searching
set incsearch " Search as characters are entered
set nohlsearch " Highlight matches
" Turn off search highlight with ',<space>'
nnoremap <leader><space> :nohlsearch<CR>


" Folding
set foldenable " Enables code folding
set foldlevelstart=10 " Open most folds by default
set foldnestmax=10 " Sets max number of folds to 10
" Maps space to open/close folds
nnoremap <space> za
set foldmethod=indent " Fold based on indent level


" Movement
" Move vertically by ~visual~ line
nnoremap j gj
nnoremap k gk
" Move to beginning/end of line
nnoremap B ^
nnoremap E $
" $/^ don't do anything
nnoremap $ <nop>
nnoremap ^ <nop>
" Highlight last inserted text
nnoremap gV '[v']

" Windows
" Natural splitting
set splitbelow
set splitright
" Create better window movement
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>


" Leader Shortcuts
let mapleader="," " Leader is comma
" jk is Esc
inoremap jk <esc>
" Save Session
nnoremap <leader>s :mksession<CR>

" Strip trailing whitespace
function! <SID>StripTrailingWhitespaces()
        let l = line(".")
        let c = col(".")
        %s/\s\+$//e
        call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()
